version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nabe-blog-container
    ports:
      - "3000:3000"
    volumes:
      - ./nabe-blog:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true